export const SliderData = [
    {
        image:
            'https://i.postimg.cc/L6MYC8vC/img1.jpg'
    },
    {
        image: 
            'https://i.postimg.cc/FHrfvCM0/img2.jpg'
    },
    {
        image:
            'https://i.postimg.cc/GmX4mJRV/img3.jpg'
    },
    {
        image:
            'https://i.postimg.cc/dtm7zcxq/img4.jpg'
    },
    {
        image:
            'https://i.postimg.cc/s21vQQDX/img5.jpg'
    },
];